definitions:
  main.Subject:
    properties:
      key:
        example: ACTURSCI
        type: string
      title:
        example: Actuarial Sciences
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: My Example API
  version: "1.0"
paths:
  /subjects:
    get:
      description: Get all string pairs as a list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Subject'
        "400":
          description: Error
          schema:
            type: string
      summary: Get course subjects
      tags:
      - subject
swagger: "2.0"
